### ISSUE TITLE
[Low] Avoid warnings by using import_tasks or include_tasks instead of include

### ISSUE THREAD

**Issue by neooleg** [nginxinc/ansible-role-nginx-oss#6]
Hi @alessfg,

thanks a lot for creating the official Nginx Ansible role!

To make clean run it make sense to avoid the following warning:
```
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 'import_tasks' for static inclusions or 'include_tasks' for dynamic
inclusions. This feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is discouraged. The module documentation details page may explain more about
this rationale.. This feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in
ansible.cfg.
```

**Comment by alessfg** [comment]
When I originally developed this version of the role I wanted to keep it as backwards compatible as possible. That being said, there is a new version of the NGINX role currently in development which will address this issue.

**Comment by alessfg** [comment]
Hi @neooleg! The new [NGINX Ansible role](https://github.com/nginxinc/ansible-role-nginx) has finally gone live and addresses this issue.

**Comment by neooleg** [comment]
Thanks @alessfg!
